export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  console.log("Montando layout global");
  return (
    <html lang="en">
      <body>
        <div> Menu principal </div>
        {children}
      </body>
    </html>
  );
}
